server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/superai?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  ai:
    openai:
      api-key:
      # ??DeepSeek
      base-url: https://api.deepseek.com
      chat:
        options:
          # ?????
          model: deepseek-chat
          # ?????? ??????????????????????????????
          temperature: 0.8
          # ?????????????????? ?-2.0?2.0??
          frequency-penalty: 0.0
          # ???????????????????????????????????????
          max-tokens: 1000
          # ??????????????????????????????????????????? n ??? 1 ???????????
          n: 1
      embedding:
        # DeepSeek API???????????
        enabled: false

    retry:
      # ???????10??
      max-attempts: 10
      backoff:
        # ???????????2??
        initial-interval: 2000ms
        # ?????????5??
        multiplier: 5
        # ???????????3???
        max-interval: 3m
      # ???????????????false?
      on-client-errors: false
      # ??????HTTP????????
      exclude-on-http-codes:
      # ?????HTTP????????
      on-http-codes:


#mybatis-plus ??
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #??????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #????
  mapper-locations: classpath*:/mapper/**/*.xml #xml????

#milvus??
milvus:
  host:
  port: 80

# OpenAi??
openai:
  api-key:

#??????
file:
  storage-dir: ./uploadedFiles

#Ai????
ai:
  enhancement:
    enabled: true  # ????AI????
    models:
      text:
        default: gpt-3.5-turbo
        long-text: claude-2
        medical: med-palm
        legal: law-gpt
      image:
        default: clip
        diagram: nougat
    thresholds:
      max-pages: 50       # ??PDF?????
      min-text-length: 100 # ???????????

# ?????
parser:
  chunk-size: 500        # ??????
  smart-chunking: true    # ???????????AI???
